### ISSUE TITLE
Function pointer structs probably should be borrowed

### ISSUE THREAD

**Issue by MaikKlein** [gwihlidal/vk-sync-rs#1]
I am currently going through the code and I noticed that the function pointer structs are not borrowed.
https://github.com/gwihlidal/vk-sync-rs/blob/master/src/cmd.rs#L10

These structs contain all the function pointers, so they are quite big. 

The fact that you are using the function pointers directly, can I assume that you would also want [ash-sys](https://github.com/MaikKlein/ash/issues/91)? It would just include the `vk.rs` file without any of the higher level functionality, like the loader.

**Comment by gwihlidal** [comment]
Ah, I didn't realize that struct is big - will pass it by ref as you mentioned.

In the case of vk-sync, I think I would be interested in ash-sys. Is there an ETA on when it will be available?

**Comment by MaikKlein** [comment]
I was just looking for a few people that would actually use it. I might be able to publish it tomorrow.

**Comment by gwihlidal** [comment]
Great, I would likely switch to it (or accept a PR if you decided to do that).

I published v0.1.2, which includes the function pointer struct borrow - thanks!
