### ISSUE TITLE
Should `AccessType` be a bitflag?

### ISSUE THREAD

**Issue by MaikKlein** [gwihlidal/vk-sync-rs#3]
```
pub struct ImageBarrier {
    pub previous_accesses: Vec<AccessType>,
    pub next_accesses: Vec<AccessType>,
    ...
}
```
Looking at `AccessType` it seems there are currently *only* 50 variants. This would fit in a `u64` bitflag.

Alternatively we could do 

```
pub struct ImageBarrier<'a> {
    pub previous_accesses: &'a [AccessType],
    pub next_accesses: &'a [AccessType],
    ...
}
```

Or is there a specific reason for the access types to be a `Vec`?

**Comment by gwihlidal** [comment]
Not going to bother (at least right now) with making it a bitfield. However, the Vec heap allocations are definitely bad, so I'm going to switch them to slice references as you suggested.
